insert into Distrito (nombre_distrito) values ('Cercado');
insert into Distrito (nombre_distrito) values ('Ancon');
insert into Distrito (nombre_distrito) values ('Ate');
insert into Distrito (nombre_distrito) values ('Barranco');
insert into Distrito (nombre_distrito) values ('Breña');
insert into Distrito (nombre_distrito) values ('Carabayllo');
insert into Distrito (nombre_distrito) values ('Comas');
insert into Distrito (nombre_distrito) values ('Chaclacayo');
insert into Distrito (nombre_distrito) values ('Chorrillos');
insert into Distrito (nombre_distrito) values ('El agustino');
insert into Distrito (nombre_distrito) values ('Jesús María');
insert into Distrito (nombre_distrito) values ('La Molina');
insert into Distrito (nombre_distrito) values ('La Victoria');
insert into Distrito (nombre_distrito) values ('Lince');
insert into Distrito (nombre_distrito) values ('Lurigancho');
insert into Distrito (nombre_distrito) values ('Lurin');
insert into Distrito (nombre_distrito) values ('Magdalena');
insert into Distrito (nombre_distrito) values ('Miraflores');
insert into Distrito (nombre_distrito) values ('Pachacamac');
insert into Distrito (nombre_distrito) values ('Pucusana');
insert into Distrito (nombre_distrito) values ('Pueblo Libre');
insert into Distrito (nombre_distrito) values ('Puente Piedra');
insert into Distrito (nombre_distrito) values ('Punta Negra');
insert into Distrito (nombre_distrito) values ('Punta Hermosa');
insert into Distrito (nombre_distrito) values ('Rimac');
insert into Distrito (nombre_distrito) values ('San Bartolo');
insert into Distrito (nombre_distrito) values ('San Isidro');
insert into Distrito (nombre_distrito) values ('Independencia');
insert into Distrito (nombre_distrito) values ('San Juan de Miraflores');
insert into Distrito (nombre_distrito) values ('San Luis');
insert into Distrito (nombre_distrito) values ('San Martin de Porres');
insert into Distrito (nombre_distrito) values ('San Miguel');
insert into Distrito (nombre_distrito) values ('Santiago de Surco');
insert into Distrito (nombre_distrito) values ('Surquillo');
insert into Distrito (nombre_distrito) values ('Villa María del Triunfo');
insert into Distrito (nombre_distrito) values ('San Juan de Lurigancho');
insert into Distrito (nombre_distrito) values ('Santa María del Mar');
insert into Distrito (nombre_distrito) values ('Santa Rosa');
insert into Distrito (nombre_distrito) values ('Los Olivos');
insert into Distrito (nombre_distrito) values ('Cieneguilla');
insert into Distrito (nombre_distrito) values ('San Borja');
insert into Distrito (nombre_distrito) values ('Villa el Salvador');
insert into Distrito (nombre_distrito) values ('Santa Anita');


